const interestsList = [
  "Music",
  "Concerts",
  "Movies",
  "Theater",
  "Painting",
  "Photography",
  "Writing",
  "Dancing",
  "Museums",
  "Running",
  "Yoga",
  "Gym",
  "Hiking",
  "Cycling",
  "Swimming",
  "Team Sports",
  "Martial Arts",
  "Surfing",
  "Skiing",
  "Camping",
  "Fishing",
  "Gardening",
  "Bird Watching",
  "Stargazing",
  "Cooking",
  "Baking",
  "Wine Tasting",
  "Craft Beer",
  "Dining Out",
  "Vegetarian",
  "Vegan Cuisine",
  "Traveling",
  "Backpacking",
  "Road Trips",
  "Adventure Sports",
  "Exploring Cultures",
  "Video Games",
  "Board Games",
  "Coding",
  "Robotics",
  "Virtual Reality",
  "Reading Books",
  "Book Clubs",
  "Self-Improvement",
  "Online Courses",
  "History",
  "Volunteering",
  "Socializing",
  "Networking",
  "Events and Festivals",
  "Dog Lover",
  "Cat Lover",
  "Animal Rescue",
  "Meditation",
  "Mindfulness",
  "Self-Care",
  "Fashion",
  "Makeup",
  "Designing",
  "Knitting",
  "Woodworking",
  "DIY Projects",
  "Sculpting",
  "Pottery",
  "Calligraphy",
  "Drawing",
  "Acting",
  "Stand-up Comedy",
  "Skateboarding",
  "Tennis",
  "Golf",
  "Basketball",
  "Soccer",
  "Baseball",
  "Climbing",
  "Diving",
  "Rock Climbing",
  "Kayaking",
  "Sailing",
  "Horseback Riding",
  "Hunting",
  "Nature Walks",
  "Grilling",
  "Mixology",
  "Coffee Tasting",
  "Tea Tasting",
  "Food Photography",
  "Food Blogging",
  "Home Brewing",
  "Fermenting",
  "Scuba Diving",
  "Paragliding",
  "Hot Air Ballooning",
  "Cruising",
  "Travel Blogging",
  "3D Printing",
  "Electronics",
  "Gadget Reviewing",
  "Drones",
  "Artificial Intelligence",
  "Philosophy",
  "Science Fiction",
  "Fantasy",
  "Mystery",
  "Non-Fiction",
  "Biography",
  "Public Speaking",
  "Hosting Parties",
  "Charity Work",
  "Fundraising",
  "Pet Training",
  "Aquarium Keeping",
  "Life Coaching",
  "Journaling",
  "Fitness Training",
  "Modeling",
  "Styling",
  "Jewelry Making",
  "Thrifting",
  "Leatherworking",
  "Metalworking",
  "Candle Making",
  "Soap Making",
  "Origami",
  "Singing",
  "Playing Instruments",
  "DJing",
  "Composing Music",
  "Songwriting",
  "Dance Performances",
  "Opera",
  "Ballet",
  "Healthy Eating",
  "Fitness Challenges",
  "Alternative Medicine",
  "Aromatherapy",
  "Spa Days",
  "Mental Health Advocacy",
  "Learning Languages",
  "Cultural Festivals",
  "Traditional Crafts",
  "Folklore",
  "Genealogy",
  "Recycling",
  "Sustainability",
  "Permaculture",
  "Zero Waste Lifestyle",
  "Wildlife Conservation",
  "Astronomy",
  "Physics",
  "Mathematics",
  "Chemistry",
  "Biology",
  "Geology",
  "Economics",
  "Political Science",
  "Collecting (Stamps, Coins, etc.)",
  "Puzzles",
  "Magic Tricks",
  "Trivia Games",
  "Astrology",
  "Tarot Reading",
  "Esports",
  "Fantasy Sports",
  "Blogging",
  "Vlogging",
  "Podcasting",
];

const colors = [
  "blue-gray",
  "gray",
  "brown",
  "deep-orange",
  "orange",
  "amber",
  "yellow",
  "lime",
  "light-green",
  "green",
  "teal",
  "cyan",
  "light-blue",
  "blue",
  "indigo",
  "deep-purple",
  "purple",
  "pink",
  "red",
];

const userQualificationList = [
  "High School",
  " Associate Degree",
  "Bachelor's Degree",
  "Master's Degree",
  "Doctorate (PhD)",
  "Professional Degree (MD, JD, etc.)",
  "Trade School",
  "Diploma",
  "Certification",
  "Other",
];


export { interestsList, colors, userQualificationList };
